#!/bin/sh
#/etc/init.d/EvilBrisketService
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
start)
exec sudo forever --sourceDir=/home/pi/evilbrisket/server -p /home/pi/evilbrisket/server evilbrisket.js  
;;
stop)
exec sudo forever stop --sourceDir=/usr/local/bin/server evilbrisket.js
;;
*)
echo "Usage: /etc/init.d/EvilBrisketService {start|stop}"
exit 1
;;
esac
exit 0